version: "3.8"
services:
  database:
    image: orlandopalmeira/aamysql:v2
    container_name: mysqldockercompose
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: votingapp
    ports:
      - "3307:3306" # só porque já tenho um mysql na porta 3306
    volumes:
      - ./votingappdatabase:/var/lib/mysql
    networks:
      - votingnet
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 20s
      timeout: 5s
      retries: 5

  appserver:
    build: ./AppVotos
    deploy:
      replicas: 2
    depends_on:
      database:
        condition: service_healthy
    environment: # ver application.properties
      DB_HOST: database
      DB_PORT: 3306 # deve usar a porta interna exposta pelo container da base de dados e não a exposta ao host (3307)
      DB_USER: root
      DB_PASSWORD: mysql
      DB_NAME: votingapp
      APP_DOMAIN: localhost
      VUE_SERVER: localhost
    networks:
      - votingnet

  nginx:
    image: nginx
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - appserver
    networks:
      - votingnet

  vite:
    build: ./Interface
    environment:
      VITE_BACKEND_SERVER_URL: http://nginx:8080 # Não funciona
    # env_file:
    #   - ./Interface/.env_docker
    ports:
      - "4173:4173"
    networks:
      - votingnet


networks:
  votingnet:
    name: votingnet
    driver: bridge